# ndarray

## 多维性

In [1]:
import numpy as np

In [7]:
arr = np.array(5)
print(arr)
print("arr的维度",arr.ndim)

5
arr的维度 0


In [8]:
arr = np.array([1,2,3])
print(arr)
print("arr的维度",arr.ndim)

[1 2 3]
arr的维度 1


In [10]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("arr的维度",arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度 2


## 同质性

In [11]:
arr = np.array([1,"hello"])
print(arr)
print("arr的维度",arr.ndim)

['1' 'hello']
arr的维度 1


In [12]:
arr = np.array([1,2.5])
print(arr)
print("arr的维度",arr.ndim)

[1.  2.5]
arr的维度 1


## 属性

In [4]:
arr = np.array([[1,2],[3,4],[5,6]])
print(arr)
print("arr的维度",arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.T)

[[1 2]
 [3 4]
 [5 6]]
arr的维度 2
(3, 2)
6
int64
[[1 3 5]
 [2 4 6]]


## ndarray的创建

In [5]:
arr = np.array([[1,2],[3,4],[5,6]])
print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [7]:
arr1 = np.copy(arr)
print(arr1)
arr1[0] = [1,3]
print(arr1)

[[1 2]
 [3 4]
 [5 6]]
[[1 3]
 [3 4]
 [5 6]]


In [9]:
arr = np.zeros((2,3))
print(arr)
print(arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [10]:
arr = np.ones((2,),dtype = int)
print(arr)

[1 1]


In [11]:
arr = np.full((3,4),205)
print(arr)

[[205 205 205 205]
 [205 205 205 205]
 [205 205 205 205]]


In [12]:
arr1 = np.zeros_like(arr)
print(arr1)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [13]:
arr  = np.arange(1,10,1)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [20]:
app = np.linspace(0,100,5,dtype = int)
print(app)

[  0  25  50  75 100]


In [22]:
arr = np.logspace(0,4,2,base = 2,dtype = int)
print(arr)

[ 1 16]


In [24]:
arr = np.eye(3,dtype = int)
print(arr)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [25]:
arr = np.diag([1,2,3])
print(arr)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [27]:
arr = np.random.rand(2,3)
print(arr)

[[0.0531032  0.63812788 0.65437414]
 [0.16082713 0.40158621 0.6297631 ]]


In [28]:
arr = np.random.uniform(3,6,(2,3))
print(arr)

[[5.00641439 5.39698261 3.0633176 ]
 [4.0882658  4.27435776 5.81533119]]


In [29]:
arr = np.random.randint(3,30,(2,3))
print(arr)

[[19 13  9]
 [18  7 15]]


In [30]:
# 正态分布（-3,3）
arr = np.random.randn(2,3)
print(arr)

[[-1.45664027 -1.04591842  0.93285574]
 [-1.98733138 -0.54929811 -0.65029615]]


In [32]:
# 设置随机种子
np.random.seed(20)
arr = np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]


## 数据类型

In [33]:
arr = np.array([1,0,2,0],dtype = bool)
print(arr)

[ True False  True False]


## 索引与切片

In [34]:
# 一维数组
arr = np.random.randint(1,100,20)
print(arr)

[17 63 17  8 99  7 27 14 76 59 26  4 75 76 62 78 84 58 95 33]


In [35]:
print(arr[10])

26


In [36]:
print(arr[2:5])

[17  8 99]


In [37]:
print(arr[arr>5])

[17 63 17  8 99  7 27 14 76 59 26 75 76 62 78 84 58 95 33]


In [39]:
print(arr[(arr>5) & (arr<20)])

[17 17  8  7 14]


In [8]:
# 二维数组
arr = np.random.randint(1,100,(4,8))
print(arr)

[[93 72 88 50 34 52 22  4]
 [32  3 12 46 38 65 15 83]
 [69 77 40 68 71 87 46 49]
 [50 28 90  9  3 64 38 83]]


In [9]:
print(arr[1,3])

46


In [10]:
print(arr[:,:])

[[93 72 88 50 34 52 22  4]
 [32  3 12 46 38 65 15 83]
 [69 77 40 68 71 87 46 49]
 [50 28 90  9  3 64 38 83]]


In [13]:
print(arr[1,:])
print(arr[1,2:5])

[32  3 12 46 38 65 15 83]
[12 46 38]


In [14]:
print(arr[arr>5])

[93 72 88 50 34 52 22 32 12 46 38 65 15 83 69 77 40 68 71 87 46 49 50 28
 90  9 64 38 83]


## ndarray的运算

In [17]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [16]:
# 比较
a = [1,2,3]
b = [4,5,6]
print(a+b)

[1, 2, 3, 4, 5, 6]


In [19]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[10,11,12]])
print(a+b)
print(a-b)
print(a*b)
print(a+3)

[[ 5  7  9]
 [11 13 15]
 [17 19 21]]
[[-3 -3 -3]
 [-3 -3 -3]
 [-3 -3 -3]]
[[  4  10  18]
 [ 28  40  54]
 [ 70  88 108]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
# 广播机制
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])
'''a
1 2 3
1 2 3
1 2 3
b
4 4 4
5 5 5
6 6 6
'''
print(a+b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [3]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[10,11,12]])
print(a*b)
print(a@b)

[[  4  10  18]
 [ 28  40  54]
 [ 70  88 108]]
[[ 48  54  60]
 [111 126 141]
 [174 198 222]]


## numpy中的常用函数

In [5]:
print(np.sqrt(9))
print(np.sqrt([1,4,9]))

3.0
[1. 2. 3.]


In [6]:
print(np.exp(1))

2.718281828459045


In [7]:
print(np.log(2.71))

0.9969486348916096


In [15]:
print(np.sin(np.pi/2))
print(np.cos(np.pi))

1.0
-1.0


In [16]:
arr = np.array([-1,1,2,3])
print(np.abs(arr))

[1 1 2 3]


In [17]:
print(np.power(arr,2))

[1 1 4 9]


In [20]:
print(np.round([3.2,3.5,5.81,8.1]))

[3. 4. 6. 8.]


In [21]:
arr = np.array([1.6,25.1,81.7])
print(np.ceil(arr))
print(np.floor(arr))

[ 2. 26. 82.]
[ 1. 25. 81.]


In [22]:
# 检测缺失值
np.isnan([1,2,np.nan])

array([False, False,  True])

In [24]:
arr = np.random.randint(1,20,8)
print(arr)

[ 5  1  7 17  9 16 12  6]


In [25]:
print(np.sum([1,2,3]))

6


In [26]:
print(np.mean([1,2,3]))

2.0


In [27]:
# 中位数
print(np.median([1,2,3]))

2.0


In [28]:
print(np.var([1,2,3])) # 方差
print(np.std([1,2,3])) # 平均差

0.6666666666666666
0.816496580927726


In [30]:
print(np.max(arr),np.argmax(arr))
print(np.min(arr))

17 3
1


In [32]:
# 分位数
print(np.percentile(arr,25))

5.75


In [33]:
arr = np.array([1,2,3])
print(np.sum(arr))
print(np.cumsum(arr)) # 累加
print(np.cumprod(arr)) # 累积

6
[1 3 6]
[1 2 6]


In [35]:
# 比较函数
print(np.greater(arr,2))
print(np.less(arr,2))
print(np.equal(arr,2))
print(np.equal([1,2,3],[1,2,4]))

[False False  True]
[ True False False]
[False  True False]
[ True  True False]


In [38]:
print(np.logical_not([1,0]))
print(np.logical_and([1,0],[1,0]))
print(np.logical_or([0,1,0],[1,1,1]))

[False  True]
[ True False]
[ True  True  True]


In [39]:
print(np.any([0,0,0,0]))
print(np.all(arr))

False
True


In [40]:
print(np.where(arr>0,1,0))

[1 1 1]


In [42]:
arr = np.array([1,2,3,4,5])
print(np.where(arr<3,arr,0))

[1 2 0 0 0]


In [43]:
arr = np.random.randint(1,100,50)
print(arr)
print(np.select([arr>80,(arr>=60)&(arr<=80), arr<60],["优秀","良好","及格"],default = "未知"))

[32 58 53 18 56 17 23 63 32 37 61 48 67 33 43 61 29 13 54 88 85 62 56 19
 81  1 50 60 25 57 68  3 38  9 19 64  8  5 65 48 60 74 71  7 77 66 93 30
 19 29]
['及格' '及格' '及格' '及格' '及格' '及格' '及格' '良好' '及格' '及格' '良好' '及格' '良好' '及格'
 '及格' '良好' '及格' '及格' '及格' '优秀' '优秀' '良好' '及格' '及格' '优秀' '及格' '及格' '良好'
 '及格' '及格' '良好' '及格' '及格' '及格' '及格' '良好' '及格' '及格' '良好' '及格' '良好' '良好'
 '良好' '及格' '良好' '良好' '优秀' '及格' '及格' '及格']


In [44]:
np.random.seed(0)
arr = np.random.randint(1,100,20)
print(arr)
print(np.sort(arr))

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]


In [45]:
print(np.unique(arr))

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


In [47]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
print(arr1+arr2)
print(np.concatenate((arr1,arr2)))
print(np.split(arr1,5))

[ 2  4  6  8 10]
[1 2 3 4 5 1 2 3 4 5]
[array([1]), array([2]), array([3]), array([4]), array([5])]


## 综合练习

In [1]:
import numpy as np

In [5]:
temps = np.array([28,30,29,31,32,30,29])
print(temps)
print("平均气温：%.3f"%np.mean(temps))
print("最高气温：%d"%np.max(temps))
print("最低气温：%d"%np.min(temps))
print("气温超过30的天数：%d"%len(temps[temps>30]))
print(temps[temps>30])

[28 30 29 31 32 30 29]
平均气温：29.857
最高气温：32
最低气温：28
气温超过30的天数：2
[31 32]


In [8]:
score = np.array([85,90,78,92,88])
print(score)
print(np.argmax(score))
print(np.argmin(score))
print(np.sort(score))
print(np.mean(score))
print(np.median(score))

[85 90 78 92 88]
3
2
[78 85 88 90 92]
86.6
88.0


In [12]:
np.random.seed(0)
arr = np.random.randint(0,10,(3,4))
print(arr)
print(np.max(arr,axis=0))
print(np.min(arr,axis=1))
print(np.where(arr%2==1,-1,arr))
arr[arr%2==1] = -1
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[7 9 7 6]
[0 3 2]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


In [13]:
arr = np.arange(1,13)
print(arr)
print(np.reshape(arr,(3,4)))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
np.random.seed(0)
arr = np.random.randint(0,20,(5,5))
arr[arr>10]=1
print(arr)

[[1 1 0 3 3]
 [7 9 1 1 4]
 [6 1 1 6 7]
 [1 1 5 1 8]
 [9 1 1 1 5]]


In [15]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
print(np.concatenate([a,b]))

[1 2 3 4 5 4 5 6 7 8]
